spring:
  kafka:
    bootstrap-servers: "${bootstrap.servers}"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule    required username='<YOUR_API_KEY>'   password='<YOUR_SECRET>';"
