package com.hermesworld.ais.galapagos.ccloud.apiclient;

import org.junit.jupiter.api.Test;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class ConfluentApiClientTest {

    private final static String envId = "env-k6jy6";

    private final static String clusterId = "lkc-9od7v";

    @Test
    public void testCreateApiKey() {
        ConfluentApiClient client = new ConfluentApiClient();
        Mono<Boolean> login = client.login("florian.albrecht@hermesworld.com", "FRGKtv1Gr4P6ppdzD7lB");
        StepVerifier.create(login).expectNext(true).verifyComplete();

        assertTrue(client.isLoggedIn());

        Mono<List<ApiKeyInfo>> list = client.listApiKeys(envId, clusterId);
        StepVerifier.create(list).consumeNextWith(ls -> ls.forEach(key -> System.out.println(key.getKey())))
                .verifyComplete();

//        Mono<ApiKeyInfo> newApiKey = client.createSuperUserApiKey(envId, clusterId, "Autogenerated by Galapagos");
//        StepVerifier.create(newApiKey).consumeNextWith(key -> {
//            System.out.println(key.getKey() + ": " + key.getSecret() + " (" + key.getDescription() + ")");
//        }).verifyComplete();
    }

}
