package com.hermesworld.ais.galapagos.security;

/**
 * Types of audit-relevant events provided by Galapagos.
 *
 * @author AlbrechtFlo
 *
 */
public enum GalapagosAuditEventType {

    APPLICATION_OWNER_REQUESTED, APPLICATION_OWNER_REQUEST_CANCELED, APPLICATION_OWNER_REQUEST_UPDATED, TOPIC_CREATED,
    TOPIC_DELETED, TOPIC_UPDATED, TOPIC_SUBSCRIBED, TOPIC_UNSUBSCRIBED, TOPIC_SCHEMA_ADDED,
    TOPIC_PRODUCER_APPLICATION_ADDED, TOPIC_PRODUCER_APPLICATION_REMOVED, TOPIC_OWNER_CHANGED, @Deprecated
    APPLICATION_CERTIFICATE_CREATED, APPLICATION_REGISTERED, SUBSCRIPTION_UPDATED
}
