# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
 
name: Linting; Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, next_minor ]

jobs:
  lint-and-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install modules
        run: npm i
        working-directory: ui
      - name: Run ui Tests
        run: npm run test
        working-directory: ui
      - name: Run ESLint
        run: npm run lint
        working-directory: ui
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml

